version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" # Location of pom.xml
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"  #actions are all over the build, need to clean up before can get specific
    schedule:
      interval: "weekly"
