import React from "react";
import { observer } from "mobx-react-lite";
import { FormattedMessage } from "react-intl";
import { useState } from "react";
import ImageModal from "./ImageModal";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/thumbs";
import "swiper/css/zoom";


const GalleryView = observer(({ store }) => {

    const allData = [
        {
            "date": "2025-07-16T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "cdca4655-b9c0-4d62-8248-c17d039a5af3",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "14fa872e-5f78-4024-8c70-1bdb4c3761cc",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "33238ccf-4741-4e3e-8f51-063126f364cb",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 230,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "acc1a041-409a-4863-84d4-b58fb29dab8a",
                            "encounterId": "14fa872e-5f78-4024-8c70-1bdb4c3761cc",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173628,
                    "uuid": "33238ccf-4741-4e3e-8f51-063126f364cb",
                    "url": "https://plus.unsplash.com/premium_photo-1666900440561-94dcb6865554?q=80&w=1254&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1754352000000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T01:27:08",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "98eaf3f4-5440-4a43-87b9-54c989c233a8",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1752624000000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": "male",
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107731599,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-07-16T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "af578dc5-2cf0-4d9d-8916-b05477bd9304",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "1b8678bd-285e-49d4-a7be-986e42569dc0",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "6a3b13f5-aa8a-470c-8cfe-52abf18d7995",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "ce5db386-ca54-4a63-bda5-154047663746",
                            "encounterId": "1b8678bd-285e-49d4-a7be-986e42569dc0",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 174440,
                    "uuid": "6a3b13f5-aa8a-470c-8cfe-52abf18d7995",
                    "url": "https://qa.wildme.org/wildbook_data_dir/a/f/af578dc5-2cf0-4d9d-8916-b05477bd9304/d5e59062-6dc0-455b-b84c-a47cb1c75696-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753395044000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-24T22:10:44",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "916ec3b3-e640-4c4d-abd4-acf13faa7d40",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1752624000000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107770412,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-05-14T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "c347a180-aa72-472f-9fb0-02d610eeaa11",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "1bf88927-1694-47da-802c-1abeabb1e131",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "3de3a071-8630-42ae-90a4-94fc36fefd26",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "2992310e-bca0-4c56-836d-8c4c0d286c5a",
                            "encounterId": "1bf88927-1694-47da-802c-1abeabb1e131",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173473,
                    "uuid": "3de3a071-8630-42ae-90a4-94fc36fefd26",
                    "url": "https://qa.wildme.org/wildbook_data_dir/c/3/c347a180-aa72-472f-9fb0-02d610eeaa11/16e73155-cb43-46ba-a27a-02997c192548-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753140088000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-21T23:21:28",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "98f77e8b-41fd-49a1-a776-be27249defa8",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1747180800000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "KB",
            "behavior": null,
            "measurements": [],
            "locationName": "Klufterbach",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107795805,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-07-16T16:16Z",
            "microsatelliteMarkers": [],
            "country": null,
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "1e26eeb6-c59d-4ba1-8300-454b0cab5188",
            "state": "",
            "tissueSampleIds": [
                "test"
            ],
            "biologicalMeasurements": {},
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "70e20697-66eb-46b0-b11a-e0361531134e",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                1655,
                                550,
                                370,
                                627
                            ],
                            "id": "9f46cae5-47d5-4943-922f-8f28c742b5f6",
                            "encounterId": "d3b23fdc-9e5b-430f-bcab-2acae51fa2d8",
                            "theta": 0
                        },
                        {
                            "boundingBox": [
                                193,
                                377,
                                909,
                                685
                            ],
                            "id": "b4b002a9-d939-4bbe-ae81-044971e6102e",
                            "encounterId": "1e26eeb6-c59d-4ba1-8300-454b0cab5188",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173718,
                    "uuid": "70e20697-66eb-46b0-b11a-e0361531134e",
                    "url": "https://qa.wildme.org/wildbook_data_dir/e/6/e6061728-74e4-43b3-b7a8-0e1504420ec4/c6a0e50e-e617-4d97-9057-d794c509aaac-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753809901000,
            "patterningCode": null,
            "annotationIAClasses": [
                "giraffe_whole"
            ],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-29T17:25:01",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 1,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "7dfbc57c-1212-463d-9077-8d07b7ed6860",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1752682560000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107918324,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": [
                "down"
            ]
        },
        {
            "date": "2025-04-13T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "1e2bddf6-c08c-4966-b4d1-8e5862afcde8",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "occurrenceGroupBehavior": null,
            "verbatimEventDate": null,
            "mediaAssets": [],
            "verbatimLocality": null,
            "numberMediaAssets": 0,
            "metalTags": [],
            "version": 1753147977000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T01:32:57",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "283e598d-3d33-4c93-a4ef-c22217708340",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1744502400000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "VB",
            "behavior": null,
            "measurements": [],
            "locationName": "Venner Bach",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107919334,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-01-10T10:10Z",
            "microsatelliteMarkers": [],
            "country": null,
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "1ea77974-20fe-4362-811d-59e1e4d90a1f",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "occurrenceGroupBehavior": null,
            "verbatimEventDate": null,
            "mediaAssets": [],
            "verbatimLocality": null,
            "numberMediaAssets": 0,
            "metalTags": [],
            "version": 1753148774000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T01:46:14",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "def99bbd-42f8-43a8-bf59-bc717e496253",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1736503800000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107946945,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-06-15T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "1f1a1505-9098-4fd8-9a79-0cbd58023a6f",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "occurrenceGroupBehavior": null,
            "verbatimEventDate": null,
            "mediaAssets": [],
            "verbatimLocality": null,
            "numberMediaAssets": 0,
            "metalTags": [],
            "version": 1753148106000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T01:35:06",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "279b9905-27e8-4a84-850f-862b1d043e76",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1749945600000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107978754,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-05-14T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "ba9fdd12-eb12-4039-a4e9-d22f2f68bcfc",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.01.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "087b4e41-dd13-440e-94d0-17e258368f23",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "84ed2a65-4650-439d-8492-3e24995010d7",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "f8db89eb-ae9c-46e9-9f5e-dbb8d7bb3437",
                            "encounterId": "087b4e41-dd13-440e-94d0-17e258368f23",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173078,
                    "uuid": "84ed2a65-4650-439d-8492-3e24995010d7",
                    "url": "https://qa.wildme.org/wildbook_data_dir/b/a/ba9fdd12-eb12-4039-a4e9-d22f2f68bcfc/78abf5fd-52d1-45a0-af74-6219419e71e2-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1752542392000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-15T01:19:52",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "38768566-fb4c-49f4-9a9b-55da5263cff0",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1747180800000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "VB-A",
            "behavior": null,
            "measurements": [],
            "locationName": "Venner Bach A",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732138,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-03-17T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "1a40544e-4b00-4f56-a474-50e7b7f50e52",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi_thornicrofti",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "0b289445-7de3-4acd-9105-f3be1dde0dbe",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "85abb245-9c08-4e69-ae1c-6cd257fb6dae",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "66707d6c-ab25-4394-b91b-ae49b6ecacc2",
                            "encounterId": "0b289445-7de3-4acd-9105-f3be1dde0dbe",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173398,
                    "uuid": "85abb245-9c08-4e69-ae1c-6cd257fb6dae",
                    "url": "https://qa.wildme.org/wildbook_data_dir/1/a/1a40544e-4b00-4f56-a474-50e7b7f50e52/0e6b505c-7ba8-4493-9caf-4b65f44f455a-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753134197000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-21T21:43:17",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "58473790-14e5-49aa-8f1f-b3cd534a09d9",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1742169600000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "VB-A",
            "behavior": null,
            "measurements": [],
            "locationName": "Venner Bach A",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732222,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-03-12T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "180a5ee7-74ff-47b1-aa99-f21067fa8a0b",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "10d86ad3-6e4a-41ae-bcfe-dd001992ba49",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "e5601181-25c0-4e90-80a9-d966bfa64742",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "e1d862b1-82e0-40cb-904f-d3bb6510e641",
                            "encounterId": "10d86ad3-6e4a-41ae-bcfe-dd001992ba49",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173439,
                    "uuid": "e5601181-25c0-4e90-80a9-d966bfa64742",
                    "url": "https://qa.wildme.org/wildbook_data_dir/1/8/180a5ee7-74ff-47b1-aa99-f21067fa8a0b/58c60abf-f193-46e2-99bd-870a085e4ea2-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753135706000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-21T22:08:26",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "bfa41b37-2057-42cb-8264-0a117d02cb32",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1741737600000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "VB-A",
            "behavior": null,
            "measurements": [],
            "locationName": "Venner Bach A",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732233,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-01-10T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "180a5ee7-74ff-47b1-aa99-f21067fa8a0b",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "0bfe9cc3-b78c-42c7-abe3-a5f1061a114e",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "verbatimEventDate": null,
            "mediaAssets": [],
            "verbatimLocality": null,
            "numberMediaAssets": 0,
            "metalTags": [],
            "version": 1753135706000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-21T22:08:26",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "01db801e-6d2f-4754-aaa7-fdbc2b14bd74",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1736467200000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "VB-A",
            "behavior": null,
            "measurements": [],
            "locationName": "Venner Bach A",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732239,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-07-16T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "c347a180-aa72-472f-9fb0-02d610eeaa11",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "19347647-f155-4169-815b-aafb1619b58f",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "18cb41d8-28e8-46a8-9f03-5f38bf6740da",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "6dfea9cc-4429-4653-bc7d-fe38b9cd9990",
                            "encounterId": "19347647-f155-4169-815b-aafb1619b58f",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173475,
                    "uuid": "18cb41d8-28e8-46a8-9f03-5f38bf6740da",
                    "url": "https://qa.wildme.org/wildbook_data_dir/c/3/c347a180-aa72-472f-9fb0-02d610eeaa11/108df620-6555-44d9-ace9-baa75cb9e656-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753140088000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-21T23:21:28",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "7d33417f-3441-4334-b750-71bb3857874e",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1752624000000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "KB",
            "behavior": null,
            "measurements": [],
            "locationName": "Klufterbach",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732246,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-01-10T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "c347a180-aa72-472f-9fb0-02d610eeaa11",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "04833c37-b7db-4262-8f56-e000f9a414fc",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "8193ef93-d0e9-486e-b2d9-ac08414c9761",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "43f795b3-967b-43e9-b70f-1e11062ccd6b",
                            "encounterId": "04833c37-b7db-4262-8f56-e000f9a414fc",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173471,
                    "uuid": "8193ef93-d0e9-486e-b2d9-ac08414c9761",
                    "url": "https://qa.wildme.org/wildbook_data_dir/c/3/c347a180-aa72-472f-9fb0-02d610eeaa11/e72e91c1-ded6-466d-86d8-740b7f0d3a30-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753140088000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-21T23:21:28",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "d419ad05-6993-4a64-866a-2e1b4b181b1d",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1736467200000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "KB",
            "behavior": null,
            "measurements": [],
            "locationName": "Klufterbach",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732252,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "d4243ee9-db72-4427-84fd-0487d8bf1cd5",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "029bb084-b65f-46e9-819d-feb90ba945d6",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "verbatimEventDate": null,
            "mediaAssets": [],
            "verbatimLocality": null,
            "numberMediaAssets": 0,
            "metalTags": [],
            "version": 1753146824000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T01:13:44",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "a104f593-f9c7-48ee-b011-c7f762b38804",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1704067200000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732264,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-03-12T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "7fe2fe25-149c-4f02-86b1-3b1b0c50d08c",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "0c2287d8-96d1-4d3b-9a21-9c7328ef4089",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "verbatimEventDate": null,
            "mediaAssets": [],
            "verbatimLocality": null,
            "numberMediaAssets": 0,
            "metalTags": [],
            "version": 1753147378000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T01:22:58",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "91f959bf-74f2-4cb3-be2f-684b7bd587ab",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1741737600000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732271,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-01-10T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "7fe2fe25-149c-4f02-86b1-3b1b0c50d08c",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "0acb7dfd-a61d-4849-8ff9-4ed309358053",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "verbatimEventDate": null,
            "mediaAssets": [],
            "verbatimLocality": null,
            "numberMediaAssets": 0,
            "metalTags": [],
            "version": 1753147378000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T01:22:58",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "355def28-0458-47be-81e3-96367735b66c",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1736467200000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732277,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-05-14T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "7fe2fe25-149c-4f02-86b1-3b1b0c50d08c",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "0b06840f-0d19-4b83-9981-c0261926d0fd",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "bfc3c197-cf41-4ed7-8e85-55cc11a5e13b",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "f79e80ff-8b82-4a6e-b0a7-6a30e80fd7d3",
                            "encounterId": "0b06840f-0d19-4b83-9981-c0261926d0fd",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173570,
                    "uuid": "bfc3c197-cf41-4ed7-8e85-55cc11a5e13b",
                    "url": "https://qa.wildme.org/wildbook_data_dir/7/f/7fe2fe25-149c-4f02-86b1-3b1b0c50d08c/fff3b032-a053-46ed-8291-21a76a12d336-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753147378000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T01:22:58",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "0c6c72be-27a7-4b60-a6fe-e63edf9a81cd",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1747180800000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732285,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-03-12T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "cdca4655-b9c0-4d62-8248-c17d039a5af3",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "0c68e1fa-fa9d-4bd3-8bab-63c3f606c94b",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "24567c86-1782-457b-997d-a6500469de52",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "80a3760e-431e-4c8d-afbc-854a21cca18e",
                            "encounterId": "0c68e1fa-fa9d-4bd3-8bab-63c3f606c94b",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173624,
                    "uuid": "24567c86-1782-457b-997d-a6500469de52",
                    "url": "https://qa.wildme.org/wildbook_data_dir/c/d/cdca4655-b9c0-4d62-8248-c17d039a5af3/e6426864-1358-40eb-9768-dd100e5e9922-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753147628000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T01:27:08",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "e5aa2584-14a5-4ba0-b20e-faa1c3e616c4",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1741737600000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732296,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-01-10T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "cdca4655-b9c0-4d62-8248-c17d039a5af3",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "09e0a74a-fa3c-4202-9620-f973de2bdb68",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "verbatimEventDate": null,
            "mediaAssets": [],
            "verbatimLocality": null,
            "numberMediaAssets": 0,
            "metalTags": [],
            "version": 1753147628000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T01:27:08",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "4b879070-1582-48bc-bf91-f5c5899547d2",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1736467200000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732302,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-05-14T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "cdca4655-b9c0-4d62-8248-c17d039a5af3",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "18a202ca-fa81-4957-9903-fbab9a93105a",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "2a619d73-e46a-4d03-a173-23d4255ac185",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "da65c17e-b4af-43bf-9575-1e608f234b0e",
                            "encounterId": "18a202ca-fa81-4957-9903-fbab9a93105a",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173626,
                    "uuid": "2a619d73-e46a-4d03-a173-23d4255ac185",
                    "url": "https://qa.wildme.org/wildbook_data_dir/c/d/cdca4655-b9c0-4d62-8248-c17d039a5af3/8dcbe810-b6e2-4e2b-ab64-0d5ecace5f76-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753147628000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T01:27:08",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "f1e772e3-0310-4cca-891d-b19a0078d567",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1747180800000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732311,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-03-12T12:12Z",
            "microsatelliteMarkers": [],
            "country": null,
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "0f561496-54b5-4590-972d-f60510b7fedc",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "6622abff-53cc-49fc-9ae6-91a87026418d",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "7517a73b-391c-4af1-bc6d-f2f479d6ff06",
                            "encounterId": "0f561496-54b5-4590-972d-f60510b7fedc",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173714,
                    "uuid": "6622abff-53cc-49fc-9ae6-91a87026418d",
                    "url": "https://qa.wildme.org/wildbook_data_dir/e/6/e6061728-74e4-43b3-b7a8-0e1504420ec4/3f22db99-4716-4f6c-a18e-0a0067bd195f-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753148774000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T01:46:14",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "9394ccca-cef5-4c4e-88b4-969b4a8d99e2",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1741781520000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732325,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-04-13T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "c5428d70-c6d9-4c4a-aadc-df9a0a547186",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "15b970a3-2c22-45bf-a537-4bd36a20c73e",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "c6867254-1909-438b-bdef-c1f1c0f89012",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "01c50cce-29b2-491c-9c29-8f94d60813fc",
                            "encounterId": "15b970a3-2c22-45bf-a537-4bd36a20c73e",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173657,
                    "uuid": "c6867254-1909-438b-bdef-c1f1c0f89012",
                    "url": "https://qa.wildme.org/wildbook_data_dir/c/5/c5428d70-c6d9-4c4a-aadc-df9a0a547186/483fd85b-3412-4ab5-bc3f-ead90367d486-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753148186000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T01:36:26",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "670d2941-57bc-4f42-813d-9bd77f279b94",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1744502400000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "VB",
            "behavior": null,
            "measurements": [],
            "locationName": "Venner Bach",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732342,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-02-11T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "44130a9d-121f-4314-90cd-0c9e29d93ceb",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "1102d157-3d0a-4f24-afc9-e33385f9e3dd",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "verbatimEventDate": null,
            "mediaAssets": [],
            "verbatimLocality": null,
            "numberMediaAssets": 0,
            "metalTags": [],
            "version": 1753204835000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T17:20:35",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "ad26183c-757a-4a16-89fb-8355f912ceb6",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1739232000000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732388,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-03-12T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "4c39fa24-5ac3-4229-8fc2-2fb6d036344f",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "0266c791-202a-47bf-ab71-2ede118caef1",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "c36974d8-726f-49c9-b8f7-f919fa7c0864",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "3f7b59dc-a9f4-46ab-9a4c-ebc8055afd67",
                            "encounterId": "0266c791-202a-47bf-ab71-2ede118caef1",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173804,
                    "uuid": "c36974d8-726f-49c9-b8f7-f919fa7c0864",
                    "url": "https://qa.wildme.org/wildbook_data_dir/4/c/4c39fa24-5ac3-4229-8fc2-2fb6d036344f/5063af23-f994-421d-88a5-edc7bde6ecee-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753217790000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T20:56:30",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "2dcb890b-5cba-4e7a-a1aa-0d4037ec4fe5",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1741737600000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732400,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-05-14T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "d52e2835-2bcb-4d57-b504-c88f174b21bb",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "0d648141-2c2d-4f07-8c00-50ac104cc960",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "0e7a2106-b5b8-4090-8483-9a7291149461",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "d905d160-6a62-4a4a-b3d0-f93bd3878c21",
                            "encounterId": "0d648141-2c2d-4f07-8c00-50ac104cc960",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173848,
                    "uuid": "0e7a2106-b5b8-4090-8483-9a7291149461",
                    "url": "https://qa.wildme.org/wildbook_data_dir/d/5/d52e2835-2bcb-4d57-b504-c88f174b21bb/b4eaf19f-990a-432a-95bb-7eb7ce8e85c0-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753283151000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-23T15:05:51",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "ecbfc827-ad41-4ef3-b699-19e31212367c",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1747180800000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732413,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-05-14T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "0a1775d9-34a0-4dad-a2b7-314171eff8dd",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "a15441e2-2e60-4d28-9082-bb66820904e0",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "127cfe6d-8877-4b0b-b937-f1c95fdae461",
                            "encounterId": "0a1775d9-34a0-4dad-a2b7-314171eff8dd",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 174476,
                    "uuid": "a15441e2-2e60-4d28-9082-bb66820904e0",
                    "url": "https://qa.wildme.org/wildbook_data_dir/3/f/3ff35b95-07dc-40fb-b153-a2fb52f74edf/1d2df975-25de-49fa-b791-0fa79749c9cd-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753395928000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-24T22:25:28",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "e83b3621-e98f-4aa0-9f6c-b734905a382e",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1747180800000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732476,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-04-13T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "3ff35b95-07dc-40fb-b153-a2fb52f74edf",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "04e4b9af-f039-4ae5-b756-a65e7e6e7326",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "8348c4a8-8758-44f0-ac95-fa49037f0f51",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "ef679cbe-a7d6-4608-9e51-8a68376a8e18",
                            "encounterId": "04e4b9af-f039-4ae5-b756-a65e7e6e7326",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 174507,
                    "uuid": "8348c4a8-8758-44f0-ac95-fa49037f0f51",
                    "url": "https://qa.wildme.org/wildbook_data_dir/3/f/3ff35b95-07dc-40fb-b153-a2fb52f74edf/4c62819c-e20e-49f7-8161-b3212baea0cd-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753395934000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-24T22:25:34",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "07424485-4c11-46c3-b538-8248170ed26b",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1744502400000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "VB",
            "behavior": null,
            "measurements": [],
            "locationName": "Venner Bach",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732485,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "3ff35b95-07dc-40fb-b153-a2fb52f74edf",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi_thornicrofti",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "1150e2e7-ba77-4c5b-91da-c019ca74cd87",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "f2ac099e-fb43-4c16-bc83-8be58c0c8dca",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "b254aa1d-2322-40b1-8cb8-8b790945868d",
                            "encounterId": "1150e2e7-ba77-4c5b-91da-c019ca74cd87",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 174503,
                    "uuid": "f2ac099e-fb43-4c16-bc83-8be58c0c8dca",
                    "url": "https://qa.wildme.org/wildbook_data_dir/3/f/3ff35b95-07dc-40fb-b153-a2fb52f74edf/21071c47-eadb-4ed6-b422-b993228c0c7a-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753395934000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-24T22:25:34",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "02bfdaa2-95ed-4513-a1f0-2a503f4a4804",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1735689600000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107732491,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-03-12T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "8661a259-be71-462b-8446-65b4669669c0",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "1ad1e18a-ece7-4f95-9a2a-343b3646852d",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "verbatimEventDate": null,
            "mediaAssets": [],
            "verbatimLocality": null,
            "numberMediaAssets": 0,
            "metalTags": [],
            "version": 1753148125000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T01:35:25",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "0fbc37fe-4338-499b-9f24-0705c698177d",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1741737600000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755107739768,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-05-14T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "importTaskId": "180a5ee7-74ff-47b1-aa99-f21067fa8a0b",
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "importTaskSourceName": "10.8.test.02.xlsx",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "21dc1fa2-d4f4-459f-8497-9395ee4d1e9c",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "importTaskCreatorId": "9d207cda-92b8-4b95-b1ba-c98845324f45",
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "a8466727-629a-4215-9c35-6c5b936e26b4",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "0f0f731c-a3f6-4e50-865f-5f44a573c58c",
                            "encounterId": "21dc1fa2-d4f4-459f-8497-9395ee4d1e9c",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173441,
                    "uuid": "a8466727-629a-4215-9c35-6c5b936e26b4",
                    "url": "https://qa.wildme.org/wildbook_data_dir/1/8/180a5ee7-74ff-47b1-aa99-f21067fa8a0b/b4453bf7-1b8a-4d8d-9625-57289098345d-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753135706000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-21T22:08:26",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "f301a962-4845-4caa-a2ed-442a9b7b5cf2",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1747180800000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "VB-A",
            "behavior": null,
            "measurements": [],
            "locationName": "Venner Bach A",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755108147565,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        },
        {
            "date": "2025-03-12T00:00Z",
            "microsatelliteMarkers": [],
            "country": null,
            "projects": [],
            "dynamicProperties": {},
            "occurrenceLocationGeoPoint": null,
            "taxonomy": "Giraffa tippelskirchi",
            "photographers": [],
            "submitterUserId": "58c17c47-3b40-4730-adf9-918df1c65ed1",
            "occurrenceComments": "None",
            "mediaAssetLabeledKeywords": {},
            "id": "22287678-d358-4552-9c53-7671e1751c24",
            "state": "",
            "tissueSampleIds": [],
            "biologicalMeasurements": {},
            "occurrenceGroupBehavior": null,
            "featuredAssetUuid": "0ecec0e5-f117-4deb-948d-63dff15164a6",
            "verbatimEventDate": null,
            "mediaAssets": [
                {
                    "mimeTypeMinor": "jpeg",
                    "width": 2304,
                    "annotations": [
                        {
                            "boundingBox": [
                                0,
                                0,
                                2304,
                                1296
                            ],
                            "id": "e12a80d7-9fe2-4d3e-9e63-8f56bb52acb1",
                            "encounterId": "22287678-d358-4552-9c53-7671e1751c24",
                            "theta": 0
                        }
                    ],
                    "mimeTypeMajor": "image",
                    "id": 173594,
                    "uuid": "0ecec0e5-f117-4deb-948d-63dff15164a6",
                    "url": "https://qa.wildme.org/wildbook_data_dir/c/d/cdca4655-b9c0-4d62-8248-c17d039a5af3/5a80f3aa-c538-4443-a84b-21d19543d79e-master.jpg",
                    "height": 1296
                }
            ],
            "verbatimLocality": null,
            "numberMediaAssets": 1,
            "metalTags": [],
            "version": 1753147585000,
            "patterningCode": null,
            "annotationIAClasses": [],
            "occurrenceGroupComposition": null,
            "livingStatus": null,
            "dateSubmitted": "2025-07-22T01:26:25",
            "mediaAssetKeywords": [],
            "access": "full",
            "numberAnnotations": 0,
            "geneticSex": null,
            "individualId": null,
            "occurrenceId": "12b9abc7-5dac-4b13-8c74-00f5be0545bb",
            "submitters": [
                "kirk",
                "kirklarsen@proton.me",
                "58c17c47-3b40-4730-adf9-918df1c65ed1"
            ],
            "dateMillis": 1741737600000,
            "distinguishingScar": "None",
            "publiclyReadable": false,
            "locationId": "TT",
            "behavior": null,
            "measurements": [],
            "locationName": "Tümpel TT",
            "haplotype": null,
            "locationGeoPoint": null,
            "sex": null,
            "assignedUsername": "kirk",
            "informOthers": [],
            "indexTimestamp": 1755108160942,
            "otherCatalogNumbers": null,
            "lifeStage": null,
            "organizations": [
                "602aa5e7-59bb-49ee-8e6e-112aeeb82c89"
            ],
            "occurrenceRemarks": "",
            "annotationViewpoints": []
        }
    ]

    const [imageModalOpen, setImageModalOpen] = useState(false);
    const [currentIndex, setCurrentIndex] = useState(0);

    const allMediaAssets = allData.filter(
        (item) => item.mediaAssets.length > 0
    ).flatMap((item) => item.mediaAssets);

    return (
        <div style={{ color: "white" }}>
            <h1>
                <FormattedMessage id="galleryView.title" defaultMessage="Gallery View" />
            </h1>
            <div style={{ display: "flex", flexWrap: "wrap", gap: "20px" }}>
                {
                    allMediaAssets.length > 0 ? allMediaAssets.map((asset, i) => (
                        <div key={asset.uuid} style={{ marginBottom: "20px" }}>
                            <img
                                src={asset.url}
                                alt={`Media Asset ${asset.id}`}
                                style={{ height: 200, width: "auto", maxWidth: 300, cursor: "zoom-in" }}
                                onClick={() => {
                                    setCurrentIndex(i);
                                    setImageModalOpen(true);
                                }}
                            />
                        </div>
                    )) : (
                        <p><FormattedMessage id="NO_IMAGE_AVAILABLE" /></p>
                    )
                }
            </div>

            <ImageModal
                open={true}
                onClose={() => setImageModalOpen(false)}
                assets={allMediaAssets}
                index={currentIndex}
                setIndex={setCurrentIndex} 
                />

        </div>

    );
});

export default GalleryView;