echo \ * building...
./mavenBuild.sh
echo \ * containers down...
docker-compose down
echo \ * cleaning cache...
sudo rm -rf /data/tomcat10/wildbook_docker_webapps/wildbook* 
echo \ * copying resources...
sudo cp target/wildbook-7.0.0-EXPERIMENTAL.war /data/tomcat10/wildbook_docker_webapps/wildbook.war


echo \ * starting containers...
docker-compose up db wildbook

echo \ * building frontend...
cd /home/ubuntu/workspace/Wildbook_tomcat9dev/frontend/ && npm run build

# echo \ * mkdir react...
# sudo mkdir -p /data/tomcat10/wildbook_docker_webapps/wildbook/react

# echo \ * copying frontend...
# sudo cp -r /home/ubuntu/workspace/Wildbook_tomcat9dev/frontend/build/* /data/tomcat10/wildbook_docker_webapps/wildbook/react/

