#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${WBIA_DB_USER} WITH SUPERUSER PASSWORD '${WBIA_DB_PASSWORD}';
    CREATE DATABASE ${WBIA_DB_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${WBIA_DB_NAME} TO ${WBIA_DB_USER};
EOSQL
