export const MOCK_DATA = {
  viewMode: "individual",
  encounterId: "sdf9-sdaw-f624-4d3",
  individualId: null, 
  projectName: "Giraffe Conservation Project",
  evaluatedAt: "2024/02/29 7:34 PM",
  numResults: 12,
  numCandidates: 2343,
  thisEncounterImageUrl:
    "https://images.pexels.com/photos/667205/pexels-photo-667205.jpeg",
  possibleMatchImageUrl:
    "https://images.pexels.com/photos/667205/pexels-photo-667205.jpeg",

  algorithms: [
    {
      id: "miewId",
      label: "Matches Based on MIEW ID Algorithm",
      matches: [
        {
          rank: 1,
          score: 0.8315,
          encounterId: "123",
          individualId: "TC_00124",
        },
        {
          rank: 2,
          score: 0.8315,
          encounterId: "456",
          individualId: "TC_00126",
        },
        {
          rank: 3,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00125",
        },
        {
          rank: 4,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00127",
        },
        {
          rank: 5,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00130",
        },
        {
          rank: 6,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00129",
        },
        {
          rank: 7,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00131",
        },
        {
          rank: 8,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00128",
        },
        {
          rank: 9,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00135",
        },
        {
          rank: 10,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00133",
        },
        {
          rank: 11,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00134",
        },
        {
          rank: 12,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00132",
        },
        {
          rank: 1,
          score: 0.8315,
          encounterId: "123",
          individualId: "TC_00124",
        },
        {
          rank: 2,
          score: 0.8315,
          encounterId: "456",
          individualId: "TC_00126",
        },
        {
          rank: 3,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00125",
        },
        {
          rank: 4,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00127",
        },
        {
          rank: 5,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00130",
        },
        {
          rank: 6,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00129",
        },
        {
          rank: 7,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00131",
        },
        {
          rank: 8,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00128",
        },
        {
          rank: 9,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00135",
        },
        {
          rank: 10,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00133",
        },
        {
          rank: 11,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00134",
        },
        {
          rank: 12,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00132",
        },
      ],
    },
    {
      id: "hotspotter",
      label: "Matches Based on Hotspotter",
      matches: [
        {
          rank: 1,
          score: 0.8315,
          encounterId: "789",
          individualId: "TC_00124",
        },
        {
          rank: 2,
          score: 0.8315,
          encounterId: "000",
          individualId: "TC_00126",
        },
        {
          rank: 3,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00125",
        },
        {
          rank: 4,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00127",
        },
        {
          rank: 5,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00130",
        },
        {
          rank: 6,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00129",
        },
        {
          rank: 7,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00131",
        },
        {
          rank: 8,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00128",
        },
        {
          rank: 9,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00135",
        },
        {
          rank: 10,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00133",
        },
        {
          rank: 11,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00134",
        },
        {
          rank: 12,
          score: 0.8315,
          encounterId: "test",
          individualId: "TC_00132",
        },
      ],
    },
  ],
};