#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${WILDBOOK_DB_USER} WITH SUPERUSER PASSWORD '${WILDBOOK_DB_PASSWORD}';
    CREATE DATABASE ${WILDBOOK_DB_NAME};
    GRANT ALL PRIVILEGES ON DATABASE ${WILDBOOK_DB_NAME} TO ${WILDBOOK_DB_USER};
EOSQL
