
-- Occurrence.occurrenceID => .id

alter table "OCCURRENCE" rename COLUMN "OCCURRENCEID" to "ID";

ALTER TABLE "OCCURRENCE_ASSETS" DROP CONSTRAINT "OCCURRENCE_ASSETS_FK1";
ALTER TABLE "OCCURRENCE_ASSETS" RENAME COLUMN "OCCURRENCEID_OID" TO "ID_OID";
ALTER TABLE "OCCURRENCE_ASSETS" ADD CONSTRAINT "OCCURRENCE_ASSETS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "OCCURRENCE"("ID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "OCCURRENCE_BEHAVIORS" DROP CONSTRAINT "OCCURRENCE_BEHAVIORS_FK1";
ALTER TABLE "OCCURRENCE_BEHAVIORS" RENAME COLUMN "OCCURRENCEID_OID" TO "ID_OID";
ALTER TABLE "OCCURRENCE_BEHAVIORS" ADD CONSTRAINT "OCCURRENCE_BEHAVIORS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "OCCURRENCE"("ID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "OCCURRENCE_ENCOUNTERS" DROP CONSTRAINT "OCCURRENCE_ENCOUNTERS_FK1";
ALTER TABLE "OCCURRENCE_ENCOUNTERS" RENAME COLUMN "OCCURRENCEID_OID" TO "ID_OID";
ALTER TABLE "OCCURRENCE_ENCOUNTERS" ADD CONSTRAINT "OCCURRENCE_ENCOUNTERS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "OCCURRENCE"("ID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "OCCURRENCE_INFORMOTHERS" DROP CONSTRAINT "OCCURRENCE_INFORMOTHERS_FK1";
ALTER TABLE "OCCURRENCE_INFORMOTHERS" RENAME COLUMN "OCCURRENCEID_OID" TO "ID_OID";
ALTER TABLE "OCCURRENCE_INFORMOTHERS" ADD CONSTRAINT "OCCURRENCE_INFORMOTHERS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "OCCURRENCE"("ID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "OCCURRENCE_OBSERVATIONS" DROP CONSTRAINT "OCCURRENCE_OBSERVATIONS_FK1";
ALTER TABLE "OCCURRENCE_OBSERVATIONS" RENAME COLUMN "OCCURRENCEID_OID" TO "ID_OID";
ALTER TABLE "OCCURRENCE_OBSERVATIONS" ADD CONSTRAINT "OCCURRENCE_OBSERVATIONS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "OCCURRENCE"("ID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "OCCURRENCE_SUBMITTERS" DROP CONSTRAINT "OCCURRENCE_SUBMITTERS_FK1";
ALTER TABLE "OCCURRENCE_SUBMITTERS" RENAME COLUMN "OCCURRENCEID_OID" TO "ID_OID";
ALTER TABLE "OCCURRENCE_SUBMITTERS" ADD CONSTRAINT "OCCURRENCE_SUBMITTERS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "OCCURRENCE"("ID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "OCCURRENCE_TAXONOMIES" DROP CONSTRAINT "OCCURRENCE_TAXONOMIES_FK1";
ALTER TABLE "OCCURRENCE_TAXONOMIES" RENAME COLUMN "OCCURRENCEID_OID" TO "ID_OID";
ALTER TABLE "OCCURRENCE_TAXONOMIES" ADD CONSTRAINT "OCCURRENCE_TAXONOMIES_FK1" FOREIGN KEY ("ID_OID") REFERENCES "OCCURRENCE"("ID") DEFERRABLE INITIALLY DEFERRED;


-- Encounter.catalogNumber => .id

BEGIN;

alter table "ENCOUNTER" rename COLUMN "CATALOGNUMBER" to "ID";


ALTER TABLE "ENCOUNTER_ANNOTATIONS" DROP CONSTRAINT "ENCOUNTER_ANNOTATIONS_FK1";
ALTER TABLE "ENCOUNTER_ANNOTATIONS" RENAME COLUMN "CATALOGNUMBER_OID" to "ID_OID";
ALTER TABLE "ENCOUNTER_ANNOTATIONS" ADD CONSTRAINT "ENCOUNTER_ANNOTATIONS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "ENCOUNTER"("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "ENCOUNTER_IMAGES" DROP CONSTRAINT "ENCOUNTER_IMAGES_FK1";
ALTER TABLE "ENCOUNTER_IMAGES" RENAME COLUMN "CATALOGNUMBER_OID" to "ID_OID";
ALTER TABLE "ENCOUNTER_IMAGES" ADD CONSTRAINT "ENCOUNTER_IMAGES_FK1" FOREIGN KEY ("ID_OID") REFERENCES "ENCOUNTER"("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "ENCOUNTER_INFORMOTHERS" DROP CONSTRAINT "ENCOUNTER_INFORMOTHERS_FK1";
ALTER TABLE "ENCOUNTER_INFORMOTHERS" RENAME COLUMN "CATALOGNUMBER_OID" to "ID_OID";
ALTER TABLE "ENCOUNTER_INFORMOTHERS" ADD CONSTRAINT "ENCOUNTER_INFORMOTHERS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "ENCOUNTER"("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "ENCOUNTER_LEFTREFERENCESPOTS" DROP CONSTRAINT "ENCOUNTER_LEFTREFERENCESPOTS_FK1";
ALTER TABLE "ENCOUNTER_LEFTREFERENCESPOTS" RENAME COLUMN "CATALOGNUMBER_OID" to "ID_OID";
ALTER TABLE "ENCOUNTER_LEFTREFERENCESPOTS" ADD CONSTRAINT "ENCOUNTER_LEFTREFERENCESPOTS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "ENCOUNTER"("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "ENCOUNTER_MEASUREMENTS" DROP CONSTRAINT "ENCOUNTER_MEASUREMENTS_FK1";
ALTER TABLE "ENCOUNTER_MEASUREMENTS" RENAME COLUMN "CATALOGNUMBER_OID" to "ID_OID";
ALTER TABLE "ENCOUNTER_MEASUREMENTS" ADD CONSTRAINT "ENCOUNTER_MEASUREMENTS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "ENCOUNTER"("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "ENCOUNTER_METALTAGS" DROP CONSTRAINT "ENCOUNTER_METALTAGS_FK1";
ALTER TABLE "ENCOUNTER_METALTAGS" RENAME COLUMN "CATALOGNUMBER_OID" to "ID_OID";
ALTER TABLE "ENCOUNTER_METALTAGS" ADD CONSTRAINT "ENCOUNTER_METALTAGS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "ENCOUNTER"("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "ENCOUNTER_OBSERVATIONS" DROP CONSTRAINT "ENCOUNTER_OBSERVATIONS_FK1";
ALTER TABLE "ENCOUNTER_OBSERVATIONS" RENAME COLUMN "CATALOGNUMBER_OID" to "ID_OID";
ALTER TABLE "ENCOUNTER_OBSERVATIONS" ADD CONSTRAINT "ENCOUNTER_OBSERVATIONS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "ENCOUNTER"("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "ENCOUNTER_PHOTOGRAPHERS" DROP CONSTRAINT "ENCOUNTER_PHOTOGRAPHERS_FK1";
ALTER TABLE "ENCOUNTER_PHOTOGRAPHERS" RENAME COLUMN "CATALOGNUMBER_OID" to "ID_OID";
ALTER TABLE "ENCOUNTER_PHOTOGRAPHERS" ADD CONSTRAINT "ENCOUNTER_PHOTOGRAPHERS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "ENCOUNTER"("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "ENCOUNTER_RIGHTREFERENCESPOTS" DROP CONSTRAINT "ENCOUNTER_RIGHTREFERENCESPOTS_FK1";
ALTER TABLE "ENCOUNTER_RIGHTREFERENCESPOTS" RENAME COLUMN "CATALOGNUMBER_OID" to "ID_OID";
ALTER TABLE "ENCOUNTER_RIGHTREFERENCESPOTS" ADD CONSTRAINT "ENCOUNTER_RIGHTREFERENCESPOTS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "ENCOUNTER"("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "ENCOUNTER_RIGHTSPOTS" DROP CONSTRAINT "ENCOUNTER_RIGHTSPOTS_FK1";
ALTER TABLE "ENCOUNTER_RIGHTSPOTS" RENAME COLUMN "CATALOGNUMBER_OID" to "ID_OID";
ALTER TABLE "ENCOUNTER_RIGHTSPOTS" ADD CONSTRAINT "ENCOUNTER_RIGHTSPOTS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "ENCOUNTER"("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "ENCOUNTER_SPOTS" DROP CONSTRAINT "ENCOUNTER_SPOTS_FK1" ;
ALTER TABLE "ENCOUNTER_SPOTS" RENAME COLUMN "CATALOGNUMBER_OID" to "ID_OID";
ALTER TABLE "ENCOUNTER_SPOTS" ADD CONSTRAINT "ENCOUNTER_SPOTS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "ENCOUNTER"("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "ENCOUNTER_SUBMITTERS" DROP CONSTRAINT "ENCOUNTER_SUBMITTERS_FK1";
ALTER TABLE "ENCOUNTER_SUBMITTERS" RENAME COLUMN "CATALOGNUMBER_OID" to "ID_OID";
ALTER TABLE "ENCOUNTER_SUBMITTERS" ADD CONSTRAINT "ENCOUNTER_SUBMITTERS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "ENCOUNTER"("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "ENCOUNTER_TISSUESAMPLES" DROP CONSTRAINT "ENCOUNTER_TISSUESAMPLES_FK1";
ALTER TABLE "ENCOUNTER_TISSUESAMPLES" RENAME COLUMN "CATALOGNUMBER_OID" to "ID_OID";
ALTER TABLE "ENCOUNTER_TISSUESAMPLES" ADD CONSTRAINT "ENCOUNTER_TISSUESAMPLES_FK1" FOREIGN KEY ("ID_OID") REFERENCES "ENCOUNTER"("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "IMPORTTASK_ENCOUNTERS" DROP CONSTRAINT "IMPORTTASK_ENCOUNTERS_FK2";
ALTER TABLE "IMPORTTASK_ENCOUNTERS" RENAME COLUMN "CATALOGNUMBER_EID" to "ID_EID";
ALTER TABLE "IMPORTTASK_ENCOUNTERS" ADD CONSTRAINT "IMPORTTASK_ENCOUNTERS_FK2" FOREIGN KEY ("ID_EID") REFERENCES "ENCOUNTER"("ID") DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "MARKEDINDIVIDUAL_ENCOUNTERS" DROP CONSTRAINT "MARKEDINDIVIDUAL_ENCOUNTERS_FK2";
ALTER TABLE "MARKEDINDIVIDUAL_ENCOUNTERS" RENAME COLUMN "CATALOGNUMBER_EID" to "ID_EID";
ALTER TABLE "MARKEDINDIVIDUAL_ENCOUNTERS" ADD CONSTRAINT "MARKEDINDIVIDUAL_ENCOUNTERS_FK2" FOREIGN KEY ("ID_EID") REFERENCES "ENCOUNTER"("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "OCCURRENCE_ENCOUNTERS" DROP CONSTRAINT "OCCURRENCE_ENCOUNTERS_FK2";
ALTER TABLE "OCCURRENCE_ENCOUNTERS" RENAME COLUMN "CATALOGNUMBER_EID" to "ID_EID";
ALTER TABLE "OCCURRENCE_ENCOUNTERS" ADD CONSTRAINT "OCCURRENCE_ENCOUNTERS_FK2" FOREIGN KEY ("ID_EID") REFERENCES "ENCOUNTER"("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

END;
