
alter table "OCCURRENCE" rename COLUMN "OCCURRENCEID" to "ID";

ALTER TABLE "OCCURRENCE_ASSETS" DROP CONSTRAINT "OCCURRENCE_ASSETS_FK1";
ALTER TABLE "OCCURRENCE_ASSETS" RENAME COLUMN "OCCURRENCEID_OID" TO "ID_OID";
ALTER TABLE "OCCURRENCE_ASSETS" ADD CONSTRAINT "OCCURRENCE_ASSETS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "OCCURRENCE"("ID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "OCCURRENCE_BEHAVIORS" DROP CONSTRAINT "OCCURRENCE_BEHAVIORS_FK1";
ALTER TABLE "OCCURRENCE_BEHAVIORS" RENAME COLUMN "OCCURRENCEID_OID" TO "ID_OID";
ALTER TABLE "OCCURRENCE_BEHAVIORS" ADD CONSTRAINT "OCCURRENCE_BEHAVIORS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "OCCURRENCE"("ID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "OCCURRENCE_ENCOUNTERS" DROP CONSTRAINT "OCCURRENCE_ENCOUNTERS_FK1";
ALTER TABLE "OCCURRENCE_ENCOUNTERS" RENAME COLUMN "OCCURRENCEID_OID" TO "ID_OID";
ALTER TABLE "OCCURRENCE_ENCOUNTERS" ADD CONSTRAINT "OCCURRENCE_ENCOUNTERS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "OCCURRENCE"("ID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "OCCURRENCE_INFORMOTHERS" DROP CONSTRAINT "OCCURRENCE_INFORMOTHERS_FK1";
ALTER TABLE "OCCURRENCE_INFORMOTHERS" RENAME COLUMN "OCCURRENCEID_OID" TO "ID_OID";
ALTER TABLE "OCCURRENCE_INFORMOTHERS" ADD CONSTRAINT "OCCURRENCE_INFORMOTHERS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "OCCURRENCE"("ID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "OCCURRENCE_OBSERVATIONS" DROP CONSTRAINT "OCCURRENCE_OBSERVATIONS_FK1";
ALTER TABLE "OCCURRENCE_OBSERVATIONS" RENAME COLUMN "OCCURRENCEID_OID" TO "ID_OID";
ALTER TABLE "OCCURRENCE_OBSERVATIONS" ADD CONSTRAINT "OCCURRENCE_OBSERVATIONS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "OCCURRENCE"("ID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "OCCURRENCE_SUBMITTERS" DROP CONSTRAINT "OCCURRENCE_SUBMITTERS_FK1";
ALTER TABLE "OCCURRENCE_SUBMITTERS" RENAME COLUMN "OCCURRENCEID_OID" TO "ID_OID";
ALTER TABLE "OCCURRENCE_SUBMITTERS" ADD CONSTRAINT "OCCURRENCE_SUBMITTERS_FK1" FOREIGN KEY ("ID_OID") REFERENCES "OCCURRENCE"("ID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "OCCURRENCE_TAXONOMIES" DROP CONSTRAINT "OCCURRENCE_TAXONOMIES_FK1";
ALTER TABLE "OCCURRENCE_TAXONOMIES" RENAME COLUMN "OCCURRENCEID_OID" TO "ID_OID";
ALTER TABLE "OCCURRENCE_TAXONOMIES" ADD CONSTRAINT "OCCURRENCE_TAXONOMIES_FK1" FOREIGN KEY ("ID_OID") REFERENCES "OCCURRENCE"("ID") DEFERRABLE INITIALLY DEFERRED;
