-- this makes it so we can delete encounters, duh?

alter table "ENCOUNTER_ANNOTATIONS" drop constraint "ENCOUNTER_ANNOTATIONS_FK1", add constraint "ENCOUNTER_ANNOTATIONS_FK1" FOREIGN KEY ("CATALOGNUMBER_OID") REFERENCES "ENCOUNTER"("CATALOGNUMBER") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ;

alter table "OCCURRENCE_ENCOUNTERS" drop constraint "OCCURRENCE_ENCOUNTERS_FK2", add constraint "OCCURRENCE_ENCOUNTERS_FK2" FOREIGN KEY ("CATALOGNUMBER_EID") REFERENCES "ENCOUNTER"("CATALOGNUMBER") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ;


