ALTER TABLE "OCCURRENCE_ENCOUNTERS"
    DROP CONSTRAINT "OCCURRENCE_ENCOUNTERS_FK1",
    ADD CONSTRAINT "OCCURRENCE_ENCOUNTERS_FK1" FOREIGN KEY ("OCCURRENCEID_OID") REFERENCES "OCCURRENCE"("OCCURRENCEID") ON UPDATE CASCADE DEFERRABLE INITIALLY DEFERRED;
