--you cant wrap a one-liner in the quotes we need to do this, and you cant do all for tables owned by postgres- so here we are 

ALTER TABLE "ADOPTION" OWNER TO wildbook;

ALTER TABLE "ENCOUNTER_IMAGES" OWNER TO wildbook;

ALTER TABLE "DATACOLLECTIONEVENT" OWNER TO wildbook;

ALTER TABLE "GENETICANALYSIS" OWNER TO wildbook;

ALTER TABLE "IBEISIAIDENTIFICATIONMATCHINGSTATE" OWNER TO wildbook;

ALTER TABLE "IDENTITYSERVICELOG" OWNER TO wildbook;

ALTER TABLE "OCCURRENCE_OBSERVATIONS" OWNER TO wildbook;

ALTER TABLE "METALTAG" OWNER TO wildbook;

ALTER TABLE "MITOCHONDRIALDNAANALYSIS" OWNER TO wildbook;

ALTER TABLE "SEXANALYSIS" OWNER TO wildbook;

ALTER TABLE "STOREDQUERY" OWNER TO wildbook;

ALTER TABLE "STUDYSITE" OWNER TO wildbook;

ALTER TABLE "SURVEYTRACK" OWNER TO wildbook;

ALTER TABLE "ABSTRACTTAG_OBSERVATIONS" OWNER TO wildbook;

ALTER TABLE "ANNOTATION_FEATURES" OWNER TO wildbook;

ALTER TABLE "MEDIAASSET" OWNER TO wildbook;

ALTER TABLE "SURVEYTRACK_OCCURRENCES" OWNER TO wildbook;

ALTER TABLE "MEASUREMENT" OWNER TO wildbook;

ALTER TABLE "ENCOUNTER_ANNOTATIONS" OWNER TO wildbook;

ALTER TABLE "OBSERVATION" OWNER TO wildbook;

ALTER TABLE "SURVEY_OBSERVATIONS" OWNER TO wildbook;

ALTER TABLE "SUPERSPOT" OWNER TO wildbook;

ALTER TABLE "OCCURRENCE_ASSETS" OWNER TO wildbook;

ALTER TABLE "OCCURRENCE_ENCOUNTERS" OWNER TO wildbook;

ALTER TABLE "MARKEDINDIVIDUAL_ENCOUNTERS" OWNER TO wildbook;

ALTER TABLE "ANNOTATION" OWNER TO wildbook;

ALTER TABLE "TAXONOMY" OWNER TO wildbook;

ALTER TABLE "SINGLEPHOTOVIDEO_KEYWORDS" OWNER TO wildbook;

ALTER TABLE "SYSTEMVALUE" OWNER TO wildbook;

ALTER TABLE "TASK_OBJECTMEDIAASSETS" OWNER TO wildbook;

ALTER TABLE "SURVEY" OWNER TO wildbook;

ALTER TABLE "USER_ROLES" OWNER TO wildbook;

ALTER TABLE "TISSUESAMPLE_ANALYSES" OWNER TO wildbook;

ALTER TABLE "TASK_OBJECTANNOTATIONS" OWNER TO wildbook;

ALTER TABLE "TASK" OWNER TO wildbook;

ALTER TABLE "SURVEY_SURVEYTRACKS" OWNER TO wildbook;

ALTER TABLE "SINGLEPHOTOVIDEO" OWNER TO wildbook;

ALTER TABLE "FEATURE" OWNER TO wildbook;

ALTER TABLE "COLLABORATIONS" OWNER TO wildbook;

ALTER TABLE "ACCESSCONTROL" OWNER TO wildbook;

ALTER TABLE "DELETEME1544749160706" OWNER TO wildbook;

ALTER TABLE "TASK_CHILDREN" OWNER TO wildbook;

ALTER TABLE "TISSUESAMPLE" OWNER TO wildbook;

ALTER TABLE "WILDBOOKSCHEDULEDTASK" OWNER TO wildbook;

ALTER TABLE "USERS" OWNER TO wildbook;

ALTER TABLE "DELETEME1547682521329" OWNER TO wildbook;

ALTER TABLE "DELETEME1550271385129" OWNER TO wildbook;

ALTER TABLE "DELETEME1556646658892" OWNER TO wildbook;

ALTER TABLE "ENCOUNTER_INFORMOTHERS" OWNER TO wildbook;

ALTER TABLE "ACOUSTICTAG" OWNER TO wildbook;

ALTER TABLE "DTAG" OWNER TO wildbook;

ALTER TABLE "ENCOUNTER_LEFTREFERENCESPOTS" OWNER TO wildbook;

ALTER TABLE "ENCOUNTER_MEASUREMENTS" OWNER TO wildbook;

ALTER TABLE "ENCOUNTER_METALTAGS" OWNER TO wildbook;

ALTER TABLE "ENCOUNTER_OBSERVATIONS" OWNER TO wildbook;

ALTER TABLE "ENCOUNTER_PHOTOGRAPHERS" OWNER TO wildbook;

ALTER TABLE "ENCOUNTER_RIGHTREFERENCESPOTS" OWNER TO wildbook;

ALTER TABLE "ENCOUNTER_RIGHTSPOTS" OWNER TO wildbook;

ALTER TABLE "ENCOUNTER_SPOTS" OWNER TO wildbook;

ALTER TABLE "ENCOUNTER" OWNER TO wildbook;

ALTER TABLE "ASSETSTORE" OWNER TO wildbook;

ALTER TABLE "FEATURETYPE" OWNER TO wildbook;

ALTER TABLE "ENCOUNTER_SUBMITTERS" OWNER TO wildbook;

ALTER TABLE "ENCOUNTER_TISSUESAMPLES" OWNER TO wildbook;

ALTER TABLE "LOCUS" OWNER TO wildbook;

ALTER TABLE "KEYWORD" OWNER TO wildbook;

ALTER TABLE "MEDIAASSETMETADATA" OWNER TO wildbook;

ALTER TABLE "MARKEDINDIVIDUAL" OWNER TO wildbook;

ALTER TABLE "MEDIAASSET_FEATURES" OWNER TO wildbook;

ALTER TABLE "RELATIONSHIP" OWNER TO wildbook;

ALTER TABLE "PATTERNINGPASSPORT" OWNER TO wildbook;

ALTER TABLE "SATELLITETAG" OWNER TO wildbook;

ALTER TABLE "MEDIAASSET_KEYWORDS" OWNER TO wildbook;

ALTER TABLE "POINTLOCATION" OWNER TO wildbook;

ALTER TABLE "SCANTASK" OWNER TO wildbook;

ALTER TABLE "OCCURRENCE" OWNER TO wildbook;
