

// recaptcha and form security 


var captchaWidgetId;
function onloadCallback() {
    captchaWidgetId = grecaptcha.render('myCaptcha', {
        'sitekey' : '<%=recaptchaProps.getProperty("siteKey") %>',  // required
        'theme' : 'light'
    });
}

function sendAttempt() {
    if(($('#myCaptcha > *').length < 1)){
        $("#encounterForm").attr("action", "EncounterForm");
        submitForm();
    } else {	
        var recaptachaResponse = grecaptcha.getResponse( captchaWidgetId );
        console.log( 'g-recaptcha-response: ' + recaptachaResponse );
        if(!isEmpty(recaptachaResponse)) {
            $("#encounterForm").attr("action", "EncounterForm");
            submitForm();
        }
    }
}

// file selection and form switching

var maxBytes = 104857600; // This is 100mb.. Do something else? I dunno.
function updateSelected(inp) {
    var f = '';
    if (inp.files && inp.files.length) {
        var all = [];
        for (var i = 0 ; i < inp.files.length ; i++) {
            if (inp.files[i].size > maxBytes) {
                all.push('<span class="error">' + inp.files[i].name + ' (' + Math.round(inp.files[i].size / (1024*1024)) + 'MB is too big, 100MB max upload size.)</span>');
            } else {
                all.push(inp.files[i].name + ' (' + Math.round(inp.files[i].size / 1024) + 'k)');
            }
        }
        f = '<b>' + inp.files.length + ' file' + ((inp.files.length == 1) ? '' : 's') + ':</b> ' + all.join(', ');
    } else {
        f = inp.value;
    }
    document.getElementById('input-file-list').innerHTML = f;
} 

function continueButtonClicked() {
    $(".form-file-selection").hide();
    $(".form-define-metadata").show();
    $("#continueButton").hide();
    $("#backButton").show();
    $("#sendButton").show();
    $(".form-define-metadata").show();
    $(".recaptcha-box").show();
}

function backButtonClicked() {
    $(".form-file-selection").show();
    $(".form-define-metadata").hide();
    $("#continueButton").show();
    $("#backButton").hide();
    $("#sendButton").hide();
    $(".recaptcha-box").hide();
}

/*
    TO DO: 

    -1. Go back and browse through the spec to make sure you arn't doing anything fucking stupid

    0. Disable continue functionality if there are no files selected or values entered.. round one validation

    0.5 look at 'updateList()' for the file input element

    1. Decide if HTML generation for each encounter/image should be generated by a seperate JS class file

    2. Fix/enable recaptcha fully

    3. Add code to preview images in page 2 form.

    4. Make a stub servlet for the form to hit

    5. think about result state- to a new jsp to wait? stick with single page?

*/

function sendButtonClicked() {

    // Send these images off to certain doom 
    
}



